[package]
name = "ex_schnorr"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ex_schnorr"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
schnorrkel = {version = "0.10.2", features=["serde"]}
rand = "0.8.4"
bincode = "1.1.4"